CC=gcc
CFLAGS=-O3 -fPIC
INCLUDES=-I${JAVA_HOME}/include/ -I${JAVA_HOME}/include/linux

OBJS = NucleotideLikelihoodCore.o

.c.o:
        ${CC} ${CFLAGS} ${INCLUDES} -c $*.c

libNucleotideLikelihoodCore.so: ${OBJS}
        ${CC} ${CFLAGS} -shared -o libNucleotideLikelihoodCore.so ${OBJS}
	