CC=gcc
CFLAGS=-O2 -funroll-loops
INCLUDES=-I${JAVA_HOME}/include/ -I${JAVA_HOME}/include/linux

OBJS = NucleotideLikelihoodCore.o

.c.o:
	${CC} ${CFLAGS} ${INCLUDES} -c $*.c

libNucleotideLikelihoodCore.so: ${OBJS}
	${CC} ${CFLAGS} ${INCLUDES} -shared -o libNucleotideLikelihoodCore.so ${OBJS}
