/*
 * ThreeDiFSlogodds.java
 *
 * Generated by logOdds_to_Q_3Di.py: exchangeability matrix and equilibrium
 * frequencies recovered from FoldSeek's 3Di log-odds substitution matrix via
 * Karlin-Altschul lambda inversion. See logodds_to_Q() for the derivation.
 *
 * Unlike Q.3Di.AF and Q.3Di.LLM, which Garg and Hochberg (2025) estimated by
 * maximum likelihood from 3Di alignments, this matrix is inverted from an
 * alignment scoring matrix and is generally the poorer fit of the three.
 *
 * NOTE: state labels A R N D C Q E G H I L K M F P S T W Y V here denote
 * Foldseek's 20 3Di structural-alphabet states, reusing amino-acid letter
 * codes as arbitrary symbols -- not actual residues.
 */

package dr.evomodel.substmodel.aminoacid;

import dr.evomodel.substmodel.EmpiricalRateMatrix;
import dr.evolution.datatype.AminoAcids;
import dr.util.Author;
import dr.util.Citation;

import java.util.Collections;
import java.util.List;

/**
 * 3Di structural-alphabet substitution model (log-odds -> Q via Karlin-Altschul lambda inversion)
 *
 * @author Generated by logOdds_to_Q_3Di.py
 */
public class ThreeDiFSlogodds extends EmpiricalRateMatrix.AbstractAminoAcid {

	public static final ThreeDiFSlogodds INSTANCE = new ThreeDiFSlogodds();

	// The rates below are specified assuming that the states are in this order:
	// ARNDCQEGHILKMFPSTWYV
	// but the AminoAcids dataType wants them in this order:
	// ACDEFGHIKLMNPQRSTVWY
	// This is solved by calling the setEmpiricalRates and setEmpiricalFrequencies methods
	private ThreeDiFSlogodds() { super("Q.3Di.FSlogodds");

		int n = AminoAcids.INSTANCE.getStateCount();

		double[][] rate = new double[n][n];

		// Q matrix
		rate[0][1]=2.4505457963669e-01; 	rate[0][2]=1.7241638252404e-01;
		rate[0][3]=1.4212952159724e+00; 	rate[0][4]=3.4829490168975e-01;
		rate[0][5]=1.4212952159724e+00; 	rate[0][6]=2.0200800909460e+00;
		rate[0][7]=4.9502987751922e-01; 	rate[0][8]=4.9502987751922e-01;
		rate[0][9]=8.5351260723184e-02; 	rate[0][10]=3.4829490168975e-01;
		rate[0][11]=3.4829490168975e-01; 	rate[0][12]=2.9727408962678e-02;
		rate[0][13]=2.8711301691426e+00; 	rate[0][14]=7.0358359668146e-01;
		rate[0][15]=8.5351260723184e-02; 	rate[0][16]=1.7241638252404e-01;
		rate[0][17]=1.0000000000000e+00; 	rate[0][18]=4.9502987751922e-01;
		rate[0][19]=1.2130933854307e-01;

		rate[1][2]=2.0200800909460e+00; 	rate[1][3]=7.0358359668146e-01;
		rate[1][4]=7.0358359668146e-01; 	rate[1][5]=4.9502987751922e-01;
		rate[1][6]=6.0051747000914e-02; 	rate[1][7]=2.8711301691426e+00;
		rate[1][8]=1.4212952159724e+00; 	rate[1][9]=3.4829490168975e-01;
		rate[1][10]=2.4505457963669e-01; 	rate[1][11]=4.2251424141908e-02;
		rate[1][12]=1.7241638252404e-01; 	rate[1][13]=1.7241638252404e-01;
		rate[1][14]=1.0000000000000e+00; 	rate[1][15]=2.0200800909460e+00;
		rate[1][16]=1.0000000000000e+00; 	rate[1][17]=1.2130933854307e-01;
		rate[1][18]=3.4829490168975e-01; 	rate[1][19]=7.0358359668146e-01;

		rate[2][3]=4.9502987751922e-01; 	rate[2][4]=1.0000000000000e+00;
		rate[2][5]=4.9502987751922e-01; 	rate[2][6]=6.0051747000914e-02;
		rate[2][7]=4.9502987751922e-01; 	rate[2][8]=1.0000000000000e+00;
		rate[2][9]=8.5351260723184e-02; 	rate[2][10]=3.4829490168975e-01;
		rate[2][11]=1.4715955617758e-02; 	rate[2][12]=4.2251424141908e-02;
		rate[2][13]=1.7241638252404e-01; 	rate[2][14]=1.0000000000000e+00;
		rate[2][15]=2.8711301691426e+00; 	rate[2][16]=2.4505457963669e-01;
		rate[2][17]=6.0051747000914e-02; 	rate[2][18]=1.7241638252404e-01;
		rate[2][19]=1.0000000000000e+00;

		rate[3][4]=4.9502987751922e-01; 	rate[3][5]=7.0358359668146e-01;
		rate[3][6]=3.4829490168975e-01; 	rate[3][7]=1.4212952159724e+00;
		rate[3][8]=1.4212952159724e+00; 	rate[3][9]=3.4829490168975e-01;
		rate[3][10]=2.4505457963669e-01; 	rate[3][11]=1.7241638252404e-01;
		rate[3][12]=1.7241638252404e-01; 	rate[3][13]=1.0000000000000e+00;
		rate[3][14]=1.4212952159724e+00; 	rate[3][15]=2.4505457963669e-01;
		rate[3][16]=4.9502987751922e-01; 	rate[3][17]=4.9502987751922e-01;
		rate[3][18]=4.9502987751922e-01; 	rate[3][19]=3.4829490168975e-01;

		rate[4][5]=1.4212952159724e+00; 	rate[4][6]=6.0051747000914e-02;
		rate[4][7]=2.4505457963669e-01; 	rate[4][8]=2.4505457963669e-01;
		rate[4][9]=1.4715955617758e-02; 	rate[4][10]=1.4212952159724e+00;
		rate[4][11]=1.0353904982147e-02; 	rate[4][12]=7.2848377070369e-03;
		rate[4][13]=1.7241638252404e-01; 	rate[4][14]=1.0000000000000e+00;
		rate[4][15]=1.0000000000000e+00; 	rate[4][16]=6.0051747000914e-02;
		rate[4][17]=8.5351260723184e-02; 	rate[4][18]=4.2251424141908e-02;
		rate[4][19]=1.4212952159724e+00;

		rate[5][6]=3.4829490168975e-01; 	rate[5][7]=2.4505457963669e-01;
		rate[5][8]=3.4829490168975e-01; 	rate[5][9]=1.2130933854307e-01;
		rate[5][10]=2.0200800909460e+00; 	rate[5][11]=1.7241638252404e-01;
		rate[5][12]=2.9727408962678e-02; 	rate[5][13]=2.0200800909460e+00;
		rate[5][14]=1.0000000000000e+00; 	rate[5][15]=2.4505457963669e-01;
		rate[5][16]=1.7241638252404e-01; 	rate[5][17]=4.9502987751922e-01;
		rate[5][18]=1.7241638252404e-01; 	rate[5][19]=7.0358359668146e-01;

		rate[6][7]=8.5351260723184e-02; 	rate[6][8]=2.4505457963669e-01;
		rate[6][9]=1.4715955617758e-02; 	rate[6][10]=8.5351260723184e-02;
		rate[6][11]=2.9727408962678e-02; 	rate[6][12]=2.5372718329982e-03;
		rate[6][13]=4.9502987751922e-01; 	rate[6][14]=1.2130933854307e-01;
		rate[6][15]=2.9727408962678e-02; 	rate[6][16]=2.9727408962678e-02;
		rate[6][17]=1.2130933854307e-01; 	rate[6][18]=3.4829490168975e-01;
		rate[6][19]=1.0353904982147e-02;

		rate[7][8]=2.8711301691426e+00; 	rate[7][9]=1.0000000000000e+00;
		rate[7][10]=8.5351260723184e-02; 	rate[7][11]=8.5351260723184e-02;
		rate[7][12]=7.0358359668146e-01; 	rate[7][13]=3.4829490168975e-01;
		rate[7][14]=4.9502987751922e-01; 	rate[7][15]=3.4829490168975e-01;
		rate[7][16]=4.0807235738364e+00; 	rate[7][17]=2.4505457963669e-01;
		rate[7][18]=4.9502987751922e-01; 	rate[7][19]=1.2130933854307e-01;

		rate[8][9]=2.4505457963669e-01; 	rate[8][10]=1.2130933854307e-01;
		rate[8][11]=8.5351260723184e-02; 	rate[8][12]=1.2130933854307e-01;
		rate[8][13]=3.4829490168975e-01; 	rate[8][14]=7.0358359668146e-01;
		rate[8][15]=3.4829490168975e-01; 	rate[8][16]=7.0358359668146e-01;
		rate[8][17]=1.7241638252404e-01; 	rate[8][18]=2.8711301691426e+00;
		rate[8][19]=1.7241638252404e-01;

		rate[9][10]=2.0915717317981e-02; 	rate[9][11]=1.7241638252404e-01;
		rate[9][12]=1.1716288564773e+01; 	rate[9][13]=1.7241638252404e-01;
		rate[9][14]=1.2130933854307e-01; 	rate[9][15]=4.2251424141908e-02;
		rate[9][16]=8.2433884481608e+00; 	rate[9][17]=1.7241638252404e-01;
		rate[9][18]=6.0051747000914e-02; 	rate[9][19]=1.4715955617758e-02;

		rate[10][11]=2.0915717317981e-02; 	rate[10][12]=3.6062123178618e-03;
		rate[10][13]=3.4829490168975e-01; 	rate[10][14]=4.9502987751922e-01;
		rate[10][15]=2.4505457963669e-01; 	rate[10][16]=4.2251424141908e-02;
		rate[10][17]=6.0051747000914e-02; 	rate[10][18]=4.2251424141908e-02;
		rate[10][19]=1.0000000000000e+00;

		rate[11][12]=6.0051747000914e-02; 	rate[11][13]=1.4212952159724e+00;
		rate[11][14]=1.2130933854307e-01; 	rate[11][15]=7.2848377070369e-03;
		rate[11][16]=1.7241638252404e-01; 	rate[11][17]=5.7999128931994e+00;
		rate[11][18]=6.0051747000914e-02; 	rate[11][19]=5.1254923151577e-03;

		rate[12][13]=4.2251424141908e-02; 	rate[12][14]=4.2251424141908e-02;
		rate[12][15]=2.9727408962678e-02; 	rate[12][16]=2.8711301691426e+00;
		rate[12][17]=1.2130933854307e-01; 	rate[12][18]=4.2251424141908e-02;
		rate[12][19]=3.6062123178618e-03;

		rate[13][14]=4.9502987751922e-01; 	rate[13][15]=6.0051747000914e-02;
		rate[13][16]=3.4829490168975e-01; 	rate[13][17]=4.0807235738364e+00;
		rate[13][18]=2.4505457963669e-01; 	rate[13][19]=8.5351260723184e-02;

		rate[14][15]=4.9502987751922e-01; 	rate[14][16]=2.4505457963669e-01;
		rate[14][17]=2.4505457963669e-01; 	rate[14][18]=1.7241638252404e-01;
		rate[14][19]=1.0000000000000e+00;

		rate[15][16]=1.2130933854307e-01; 	rate[15][17]=2.0915717317981e-02;
		rate[15][18]=4.2251424141908e-02; 	rate[15][19]=1.0000000000000e+00;

		rate[16][17]=1.7241638252404e-01; 	rate[16][18]=1.7241638252404e-01;
		rate[16][19]=4.2251424141908e-02;

		rate[17][18]=1.2130933854307e-01; 	rate[17][19]=2.9727408962678e-02;

		rate[18][19]=2.0915717317981e-02;

		setEmpiricalRates(rate, "ARNDCQEGHILKMFPSTWYV");

		double[] f = new double[n];
		f[0]=0.049; f[1]=0.026; f[2]=0.022; f[3]=0.101;
		f[4]=0.031; f[5]=0.051; f[6]=0.033; f[7]=0.042;
		f[8]=0.045; f[9]=0.031; f[10]=0.061; f[11]=0.030;
		f[12]=0.015; f[13]=0.028; f[14]=0.078; f[15]=0.061;
		f[16]=0.020; f[17]=0.031; f[18]=0.030; f[19]=0.216;

		setEmpiricalFrequencies(f, "ARNDCQEGHILKMFPSTWYV");
	}

	@Override
	public Citation.Category getCategory() {
		return Citation.Category.SUBSTITUTION_MODELS;
	}

	@Override
	public String getDescription() {
		return "3Di structural-alphabet substitution model (log-odds -> Q via Karlin-Altschul lambda inversion)";
	}

	@Override
	public List<Citation> getCitations() {
		return Collections.singletonList(CITATION);
	}

	public static Citation CITATION = new Citation(
			new Author[]{
			new Author("M", "van Kempen"),
			new Author("SS", "Kim")
			},
			"Fast and accurate protein structure search with Foldseek",
			2024,
			"Nat Biotechnol",
			42,
			243, 246,
			Citation.Status.PUBLISHED
	);
}
