/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dr_evomodel_substmodel_NativeSubstitutionModel */

#ifndef _Included_dr_evomodel_substmodel_NativeSubstitutionModel
#define _Included_dr_evomodel_substmodel_NativeSubstitutionModel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dr_evomodel_substmodel_NativeSubstitutionModel
 * Method:    nativeStoreState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dr_evomodel_substmodel_NativeSubstitutionModel_nativeStoreState
  (JNIEnv *, jobject);

/*
 * Class:     dr_evomodel_substmodel_NativeSubstitutionModel
 * Method:    nativeRestoreState
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dr_evomodel_substmodel_NativeSubstitutionModel_nativeRestoreState
  (JNIEnv *, jobject);

/*
 * Class:     dr_evomodel_substmodel_NativeSubstitutionModel
 * Method:    nativeInitialiseEigen
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dr_evomodel_substmodel_NativeSubstitutionModel_nativeInitialiseEigen
  (JNIEnv *, jobject, jint);

/*
 * Class:     dr_evomodel_substmodel_NativeSubstitutionModel
 * Method:    nativeSetup
 * Signature: ([[D[[D[D[D)V
 */
JNIEXPORT void JNICALL Java_dr_evomodel_substmodel_NativeSubstitutionModel_nativeSetup
  (JNIEnv *, jobject, jlong, jobjectArray, jobjectArray, jdoubleArray, jdoubleArray, jint);

#ifdef __cplusplus
}
#endif
#endif
