/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dr_math_SparseMatrixExponential */

#ifndef _Included_dr_math_SparseMatrixExponential
#define _Included_dr_math_SparseMatrixExponential
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dr_math_SparseMatrixExponential
 * Method:    executeDGEXPV
 * Signature: (IIID[D[DDD[D[I[I[DI[III)V
 */
JNIEXPORT void JNICALL Java_dr_math_SparseMatrixExponential_executeDGEXPV
  (JNIEnv *, jobject, jint, jint, jint, jdouble, jdoubleArray, jdoubleArray, jdouble, jdouble, jdoubleArray, jintArray, jintArray, jdoubleArray, jint, jintArray, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
