#!/bin/sh

if [ -z "$TRACER" ]; then
	## resolve links - $0 may be a link to application
	PRG="$0"

	# need this for relative symlinks
	while [ -h "$PRG" ] ; do
	    ls=`ls -ld "$PRG"`
	    link=`expr "$ls" : '.*-> \(.*\)$'`
	    if expr "$link" : '/.*' > /dev/null; then
		PRG="$link"
	    else
		PRG="`dirname "$PRG"`/$link"
	    fi
	done

	# make it fully qualified
	saveddir=`pwd`
	TRACER0=`dirname "$PRG"`/..
	TRACER=`cd "$TRACER0" && pwd`
	cd "$saveddir"
fi

TRACER_LIB=$TRACER/lib
java -Xms64m -Xmx256m -jar $TRACER_LIB/tracer.jar $*

