## Makefile.solaris
## zph@herald.ox.ac.uk 2007-08-16  Modified from Makefile.sunos

CC=gcc
CFLAGS=-O2 -funroll-loops -fstrict-aliasing

JAVA_HOME=/usr/local/sparc_pkg/jdk-1.5.0_04

INCLUDES=-I${JAVA_HOME}/include/ -I${JAVA_HOME}/include/solaris

OBJS = NucleotideLikelihoodCore.o

.c.o:
	${CC} ${CFLAGS} ${INCLUDES} -c $*.c

libNucleotideLikelihoodCore.so: ${OBJS}
	${CC} ${CFLAGS} ${INCLUDES} -mimpure-text -shared -o libNucleotideLikelihoodCore.so ${OBJS}
