#!/bin/sh

if [ -z "$PIBUSS" ]; then
	## resolve links - $0 may be a link to application
	PRG="$0"

	# need this for relative symlinks
	while [ -h "$PRG" ] ; do
	    ls=`ls -ld "$PRG"`
	    link=`expr "$ls" : '.*-> \(.*\)$'`
	    if expr "$link" : '/.*' > /dev/null; then
		PRG="$link"
	    else
		PRG="`dirname "$PRG"`/$link"
	    fi
	done

	# make it fully qualified
	saveddir=`pwd`
	PIBUSS0=`dirname "$PRG"`/..
	PIBUSS=`cd "$PIBUSS0" && pwd`
	cd "$saveddir"
fi

PIBUSS_LIB=$PIBUSS/lib
java -Xms64m -Xmx1024m -Djava.library.path="$PIBUSS_LIB:/usr/local/lib" -jar $PIBUSS_LIB/buss.jar $*

