package dr.evomodel.epidemiology.casetocase;

import dr.evolution.coalescent.Coalescent;
import dr.evolution.coalescent.DemographicFunction;
import dr.evolution.coalescent.IntervalList;
import dr.evolution.coalescent.IntervalType;
import dr.evolution.tree.FlexibleTree;
import dr.evolution.tree.Tree;
import dr.evolution.util.TaxonList;
import dr.evomodel.tree.TreeModel;
import dr.inference.model.Parameter;
import dr.math.Binomial;

/**
 * Intended to replace the tree prior; each partition is considered a tree in its own right generated by a
 * coalescent process
 *
 * @author Matthew Hall
 */

public class WithinCaseCoalescent extends CaseToCaseTreeLikelihood {

    public static final String WITHIN_CASE_COALSECENT = "withinCaseCoalescent";
    private TreePlusRootBranchLength[] partitionsAsTrees;
    private TreePlusRootBranchLength[] storedPartitionsAsTrees;
    private DemographicFunction demoFunct;

    public WithinCaseCoalescent(TreeModel virusTree, AbstractOutbreak caseData, String startingNetworkFileName,
                                    Parameter infectionTimeBranchPositions, Parameter maxFirstInfToRoot,
                                    boolean extended, boolean normalise, boolean jeffreys)
            throws TaxonList.MissingTaxonException {
        super(WITHIN_CASE_COALSECENT, virusTree, caseData, startingNetworkFileName, infectionTimeBranchPositions, null,
                maxFirstInfToRoot, extended, normalise, jeffreys);
    }


    public static double calculatePartitionLogLikelihood(IntervalList intervals,
                                                         DemographicFunction demographicFunction, double threshold,
                                                         double maxHeight) {

        double logL = 0.0;

        double startTime = 0.0;
        final int n = intervals.getIntervalCount();
        for (int i = 0; i < n; i++) {

            final double duration = intervals.getInterval(i);
            final double finishTime = startTime + duration;

            final double intervalArea = demographicFunction.getIntegral(startTime, finishTime);
            double normalisationArea = demographicFunction.getIntegral(startTime, maxHeight);

            if( intervalArea == 0 && duration != 0 ) {
                return Double.NEGATIVE_INFINITY;
            }
            final int lineageCount = intervals.getLineageCount(i);

            final double kChoose2 = Binomial.choose2(lineageCount);

            if (intervals.getIntervalType(i) == IntervalType.COALESCENT) {

                logL += -kChoose2 * intervalArea;

                final double demographicAtCoalPoint = demographicFunction.getDemographic(finishTime);

                // if value at end is many orders of magnitude different than mean over interval reject the interval
                // This is protection against cases where ridiculous infitisimal
                // population size at the end of a linear interval drive coalescent values to infinity.

                if( duration == 0.0 || demographicAtCoalPoint * (intervalArea/duration) >= threshold ) {
                    logL -= Math.log(demographicAtCoalPoint);
                } else {
                    // remove this at some stage
                    return Double.NEGATIVE_INFINITY;
                }

            } else {
                double numerator = Math.exp(kChoose2 * intervalArea) - Math.exp(kChoose2 * normalisationArea);
                logL += Math.log(numerator);

            }

            // normalisation

            double denominator = 1-Math.exp(kChoose2 * normalisationArea);

            logL -= Math.log(denominator);

            startTime = finishTime;
        }

        return logL;
    }

    // Tears the tree into small pieces. Indexes correspond to indexes in the outbreak.
    // @todo Work out when

    private void explodeTree(){



    }



    private class MaxTMRCACoalescent extends Coalescent{

        private double maxHeight;

        private MaxTMRCACoalescent(Tree tree, DemographicFunction demographicFunction, double maxHeight){
            super(tree, demographicFunction);
            this.maxHeight = maxHeight;
        }

        public double calculateLogLikelihood() {
            return calculatePartitionLogLikelihood(getIntervals(), getDemographicFunction(), 0, maxHeight);
        }

    }

    private class TreePlusRootBranchLength extends FlexibleTree {

        private double rootBranchLength;

        private TreePlusRootBranchLength(FlexibleTree tree, double rootBranchLength){
            super(tree);
            this.rootBranchLength = rootBranchLength;
        }

        private double getRootBranchLength(){
            return rootBranchLength;
        }

        private void setRootBranchLength(){
            this.rootBranchLength = rootBranchLength;
        }
    }




}
