/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dr_inference_hmc_PrecisionColumnProvider_Generic */

#ifndef _Included_dr_inference_hmc_PrecisionColumnProvider_Generic
#define _Included_dr_inference_hmc_PrecisionColumnProvider_Generic
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
