#!/bin/bash

export TRUNK=~/IdeaProjects/Beast/branches/arg
export CLASSPATH=$TRUNK/bin/:$TRUNK/lib/commons-math-1.1.jar:$TRUNK/lib/jdom.jar


if [[ "$1" -eq "" ]]
then java dr.app.beast.BeastMain all.xml
else java dr.app.beast.BeastMain -seed $1 all.xml
fi
